### ISSUE TITLE
create /invite

### ISSUE THREAD

**Issue by CyberStrike** [front-end-miami/www#1]
A simple page that redirects a visitor to our slack invite page.

https://join.slack.com/t/fedm/shared_invite/enQtMzgyMTMzNTI5NDQ3LTdiMmRjNDA2ODE5YWI0NGFmZjg0ZGUzZTUxMDg4MmJmYWI4ZWZjZDNjZjJkYmUyMThlMDVlMzA2YWY4ZWU5YWQ

### Content
```
[relevant gif/icon]
You are being redirected to.. [url]
```

### Relevant Help

https://nuxtjs.org/guide/routing#basic-routes
https://stackoverflow.com/questions/503093/how-do-i-redirect-to-another-webpage

**Comment by cdvillard** [comment]
I'll get on this tonight.
